<?php

namespace ContainerHH5Ex9k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenericIndexerService extends Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'Nramos\SearchIndexer\Indexer\GenericIndexer' shared autowired service.
     *
     * @return \Nramos\SearchIndexer\Indexer\GenericIndexer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Indexer/IndexerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Indexer/GenericIndexer.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['Nramos\\SearchIndexer\\Indexer\\GenericIndexer'])) {
            return $container->privates['Nramos\\SearchIndexer\\Indexer\\GenericIndexer'];
        }

        return $container->privates['Nramos\\SearchIndexer\\Indexer\\GenericIndexer'] = new \Nramos\SearchIndexer\Indexer\GenericIndexer($a, ($container->privates['Nramos\\SearchIndexer\\Meilisearch\\MeilisearchClient'] ?? $container->load('getMeilisearchClientService')));
    }
}
