<?php

namespace ContainerHH5Ex9k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexEntitiesCommandService extends Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'Nramos\SearchIndexer\Command\IndexEntitiesCommand' shared autowired service.
     *
     * @return \Nramos\SearchIndexer\Command\IndexEntitiesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/IndexEntitiesCommand.php';

        $container->privates['Nramos\\SearchIndexer\\Command\\IndexEntitiesCommand'] = $instance = new \Nramos\SearchIndexer\Command\IndexEntitiesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['Nramos\\SearchIndexer\\Indexer\\GenericIndexer'] ?? $container->load('getGenericIndexerService')));

        $instance->setName('search:import');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
