<?php

namespace ContainerHH5Ex9k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexEntitiesCommand_LazyService extends Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.Nramos\SearchIndexer\Command\IndexEntitiesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Nramos\\SearchIndexer\\Command\\IndexEntitiesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('search:import', [], 'Add a short description for your command', false, #[\Closure(name: 'Nramos\\SearchIndexer\\Command\\IndexEntitiesCommand')] fn (): \Nramos\SearchIndexer\Command\IndexEntitiesCommand => ($container->privates['Nramos\\SearchIndexer\\Command\\IndexEntitiesCommand'] ?? $container->load('getIndexEntitiesCommandService')));
    }
}
