<?php

namespace ContainerHH5Ex9k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeilisearchClientService extends Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'Nramos\SearchIndexer\Meilisearch\MeilisearchClient' shared service.
     *
     * @return \Nramos\SearchIndexer\Meilisearch\MeilisearchClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Indexer/SearchClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Meilisearch/MeilisearchClient.php';

        return $container->privates['Nramos\\SearchIndexer\\Meilisearch\\MeilisearchClient'] = new \Nramos\SearchIndexer\Meilisearch\MeilisearchClient('http://localhost:7700', 'your_api_key', ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
