<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0w0S0VQ\Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0w0S0VQ/Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container0w0S0VQ.legacy');

    return;
}

if (!\class_exists(Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\Container0w0S0VQ\Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer::class, Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer::class, false);
}

return new \Container0w0S0VQ\Nramos_SearchIndexer_Tests_TestKernelTestDebugContainer([
    'container.build_hash' => '0w0S0VQ',
    'container.build_id' => 'd49590cc',
    'container.build_time' => 1719758521,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0w0S0VQ');
